name: ci

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Compile
        run: ./mill __.compile
      - name: Check Formatting
        run: ./mill __.checkFormat
      - name: Check for schema updates
        run: |
          ./mill genSchema
          git diff --exit-code
      - name: Scalafix
        run: ./mill __.fix --check
      - name: Run tests
        run: ./mill __.test
      ##################
      # Coverage Stuff #
      ##################
      - name: Generate Coverage Reports
        run: ./mill __.scoverage.xmlReport
      - name: Send Coverage Reports
        uses: codecov/codecov-action@v1
        with:
          # TODO do for all modules automatically
          files: ./out/core/scoverage/xmlReport/dest/scoverage.xml,./out/persistence/scoverage/xmlReport/dest/scoverage.xml #,./out/main/scoverage/xmlReport/dest/scoverage.xml # optional
          flags: unittests # optional
          fail_ci_if_error: true # optional (default = false)
