name: ci

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Compile
        run: ./mill __.compile
      - name: Check for schema updates
        run: |
          ./mill genSchema
          git diff --exit-code
      - name: Scalafix
        run: ./mill __.fix --check
      - name: Run tests
        run: ./mill __.test
