name: ci

on:
  push:
  pull_request:
    branches:
      - master

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v2
        with:
          distribution: temurin
          java-version: 11

      - name: Compile
        run: ./mill __.compile

      - name: Check Formatting
        run: ./mill __.checkFormat

      - name: Scalafix
        run: ./mill __.fix --check

      - name: Create docker Image
        run: ./mill finito.main.docker.build

      - name: Run tests
        run: ./mill __.test

      ##################
      # Coverage Stuff #
      ##################
      - name: Generate Coverage Reports
        run: ./mill __.scoverage.xmlReport
      - name: Send Coverage Reports
        uses: codecov/codecov-action@v1
        with:
          # TODO do for all modules automatically
          files: ./out/finito/core/scoverage/xmlReport.dest/scoverage.xml,./out/finito/persistence/scoverage/xmlReport.dest/scoverage.xml #,./out/main/scoverage/xmlReport/dest/scoverage.xml # optional
          flags: unittests # optional
          fail_ci_if_error: true # optional (default = false)
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}

      ####################
      # GH Release Stuff #
      ####################
      - name: Assembly
        if: startsWith(github.ref, 'refs/tags/')
        run: ./mill finito.main.assembly
      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            out/finito/main/assembly.dest/*.jar
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
